### PR TITLE
Add ES6 support with babel on webpack

### PR DESCRIPTION
**Pull request by CVarisco**
Hi @wagenaartje !

I'm set up the environment to write in ES6 with babel on webpack.
I started to write in ES6 a couple of things:

- `const` and `let`declaration everywhere.
- Destructuring assignment

I created this PR to help you with the set up of webpack and to start writing on ES6 🙂 !

Hope you enjoy 🌴 

ps: In this way you can start writing [ES6 Class](https://github.com/wagenaartje/stocks.js/issues/3)

### CODE REVIEW

**Comment by kresli** [comment]
https://github.com/wagenaartje/stocks.js/pull/6

**Comment by wagenaartje** [comment]
Before this project, I was never aware of ES5 and ES6 style. I know understand that `Babel` is needed to convert ES6 code to ES5 code so browsers/runtimes which don't fully support ES6 can still run ES5.

However, this project is targeted for `Node >=8` and most modern browsers (so not you, IE). Looking up the browsers and Node on [this table](https://kangax.github.io/compat-table/es6/) actually gives the impression that ES6 is almost fully supported (Avg: 96%) for these platforms. 

_Do we really need Babel?_  Maybe i'm missing something

**Comment by CVarisco** [comment]
Hi!
sorry I'm busy in this period 🙁 

However, I used babel because I think that if you want that more people use your library you need to support lower version of node and different version of browsers (not only the latest).

Personally, I'm using babel almost in every project because I want use all the latest feature (ES7 included).

Of course feel free to don't accept this merge request if you don't want babel 🌮 

Hope you enjoy my clarification.
Have a nice day 🏎

**Comment by CVarisco** [comment]
I'm closing this PR because I think that isn't important 🙂

**Pull request closed without merging**
